Repository mondeja/mkdocs-include-markdown-plugin, pull requests merged in 2023-10, with the labels that each got.

#178 Drop Python upper version bound and migrate dev tools to Ruff
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  pyproject.toml
  src/mkdocs_include_markdown_plugin/__init__.py
  src/mkdocs_include_markdown_plugin/cache.py
  src/mkdocs_include_markdown_plugin/config.py
  src/mkdocs_include_markdown_plugin/directive.py
  src/mkdocs_include_markdown_plugin/event.py
  src/mkdocs_include_markdown_plugin/files_watcher.py
  src/mkdocs_include_markdown_plugin/plugin.py
  src/mkdocs_include_markdown_plugin/process.py
  tests/test_integration/test_cache_integration.py
  tests/test_integration/test_examples.py
  tests/test_unit/test_arguments.py
  tests/test_unit/test_config.py
  tests/test_unit/test_encoding.py
  tests/test_unit/test_exclude.py
  tests/test_unit/test_glob_include.py
  tests/test_unit/test_include.py
  tests/test_unit/test_include_markdown.py
  tests/test_unit/test_logging.py
  tests/test_unit/test_nested_includes.py
  tests/test_unit/test_process.py
Labels: enhancement, chore

#180 Refactor to use new static type checking features
  README.md
  locale/es/README.md
  locale/es/README.md.po
  locale/fr/README.md
  locale/fr/README.md.po
  pyproject.toml
  src/mkdocs_include_markdown_plugin/config.py
  src/mkdocs_include_markdown_plugin/directive.py
  src/mkdocs_include_markdown_plugin/event.py
  src/mkdocs_include_markdown_plugin/plugin.py
  src/mkdocs_include_markdown_plugin/process.py
  tests/conftest.py
  tests/test_integration/test_cache_integration.py
  tests/test_unit/test_arguments.py
  tests/test_unit/test_config.py
  tests/test_unit/test_encoding.py
  tests/test_unit/test_exclude.py
  tests/test_unit/test_glob_include.py
  tests/test_unit/test_include.py
  tests/test_unit/test_include_markdown.py
  tests/test_unit/test_logging.py
  tests/test_unit/test_nested_includes.py
Labels: dependencies, chore

#181 Improve coverage
  examples/global-exclude/docs/include.txt
  examples/global-exclude/docs/index.md
  pyproject.toml
  src/mkdocs_include_markdown_plugin/__init__.py
  src/mkdocs_include_markdown_plugin/cache.py
  src/mkdocs_include_markdown_plugin/directive.py
  src/mkdocs_include_markdown_plugin/event.py
  src/mkdocs_include_markdown_plugin/plugin.py
  tests/conftest.py
  tests/test_integration/test_cache_integration.py
  tests/test_integration/test_examples.py
Labels: chore

#182 Add `known-first-party` isort config
  .pre-commit-config.yaml
  pyproject.toml
  tests/test_integration/test_cache_integration.py
  tests/test_integration/test_examples.py
  tests/test_unit/test_arguments.py
  tests/test_unit/test_config.py
  tests/test_unit/test_encoding.py
  tests/test_unit/test_exclude.py
  tests/test_unit/test_glob_include.py
  tests/test_unit/test_include.py
  tests/test_unit/test_include_markdown.py
  tests/test_unit/test_logging.py
  tests/test_unit/test_nested_includes.py
  tests/test_unit/test_process.py
Labels: chore
