Repository mondeja/mkdocs-include-markdown-plugin, pull requests merged in 2023-07, with the labels that each got.

#164 Convert logger errors to build errors
  .github/workflows/ci.yml
  .github/workflows/update-gh-actions.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  codecov.yml
  examples/exclude-self/docs/README.md
  examples/exclude-self/docs/included.md
  examples/exclude-self/mkdocs.yml
  locale/es/README.md
  locale/es/README.md.po
  locale/fr/README.md
  locale/fr/README.md.po
  pyproject.toml
  src/mkdocs_include_markdown_plugin/event.py
  tests/test_unit/test_arguments.py
  tests/test_unit/test_exclude.py
  tests/test_unit/test_include.py
  tests/test_unit/test_include_markdown.py
Labels: bug fix

#161 Python 3.12 support
  .github/workflows/ci.yml
  .github/workflows/pre-commit-autoupdate.yml
  README.md
  locale/es/README.md
  locale/fr/README.md
  pyproject.toml
Labels: chore

#165 Add `cache` extra for persistent HTTP requests file caching
  .github/workflows/ci.yml
  examples/http-cache/docs/README.md
  examples/http-cache/mkdocs.yml
  pyproject.toml
  src/mkdocs_include_markdown_plugin/cache.py
  src/mkdocs_include_markdown_plugin/config.py
  src/mkdocs_include_markdown_plugin/event.py
  src/mkdocs_include_markdown_plugin/plugin.py
  tests/test_integration/test_cache.py
  tests/test_integration/test_examples.py
Labels: enhancement

#166 Add documentation for HTTP cache feature
  README.md
  locale/es/README.md
  locale/es/README.md.po
  locale/fr/README.md
  locale/fr/README.md.po
Labels: documentation

#167 Drop Python3.7 support
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  pyproject.toml
  src/mkdocs_include_markdown_plugin/event.py
Labels: chore

#168 Drop Mkdocs<1.4.0 support
  CONTRIBUTING.md
  README.md
  locale/es/README.md
  locale/es/README.md.po
  locale/fr/README.md
  locale/fr/README.md.po
  pyproject.toml
  src/mkdocs_include_markdown_plugin/plugin.py
Labels: chore
