Repository mondeja/mkdocs-include-markdown-plugin, pull requests merged in 2024-06, with the labels that each got.

#208 Add new `recursive` argument to `include` directive
  README.md
  locale/es/README.md
  locale/es/README.md.po
  locale/fr/README.md
  locale/fr/README.md.po
  pyproject.toml
  src/mkdocs_include_markdown_plugin/config.py
  src/mkdocs_include_markdown_plugin/directive.py
  src/mkdocs_include_markdown_plugin/event.py
  tests/test_unit/test_nested_includes.py
Labels: new feature

#211 Change substitutions order of directives
  pyproject.toml
  src/mkdocs_include_markdown_plugin/event.py
Labels: enhancement

#214 Warn when passing invalid arguments to directives
  README.md
  locale/es/README.md
  locale/fr/README.md
  pyproject.toml
  src/mkdocs_include_markdown_plugin/directive.py
  src/mkdocs_include_markdown_plugin/event.py
  src/mkdocs_include_markdown_plugin/logger.py
  src/mkdocs_include_markdown_plugin/process.py
  tests/test_unit/test_arguments.py
  tests/test_unit/test_exclude.py
  tests/test_unit/test_glob_include.py
  tests/test_unit/test_include.py
  tests/test_unit/test_nested_includes.py
Labels: enhancement

#216 Don't import `typing.Any` on runtime
  src/mkdocs_include_markdown_plugin/plugin.py
  src/mkdocs_include_markdown_plugin/process.py
Labels: chore

#217 Apply substitutions from all directives at once
  src/mkdocs_include_markdown_plugin/event.py
Labels: enhancement

#218 Add `recursive` argument to `include-markdown` directive
  README.md
  locale/es/README.md
  locale/es/README.md.po
  locale/fr/README.md
  locale/fr/README.md.po
  pyproject.toml
  src/mkdocs_include_markdown_plugin/directive.py
  src/mkdocs_include_markdown_plugin/event.py
  tests/test_unit/test_nested_includes.py
Labels: enhancement

#219 Use defined `encoding` when reading from URLs
  README.md
  locale/es/README.md
  locale/es/README.md.po
  locale/fr/README.md
  locale/fr/README.md.po
  src/mkdocs_include_markdown_plugin/cache.py
  src/mkdocs_include_markdown_plugin/event.py
  src/mkdocs_include_markdown_plugin/process.py
Labels: bug fix

#220 Add monthly downloads badge to README
  README.md
  locale/es/README.md
  locale/es/README.md.po
  locale/fr/README.md
  locale/fr/README.md.po
Labels: documentation

#222 Speed up inclusion regex
  .pre-commit-config.yaml
  examples/long-line/docs/index.md
  examples/long-line/mkdocs.yml
  pyproject.toml
  src/mkdocs_include_markdown_plugin/directive.py
Labels: bug fix, performance
