Repository mondeja/mkdocs-include-markdown-plugin, pull requests merged in 2025-02, with the labels that each got.

#252 Add HTML support for relative URL rewrites
  src/mkdocs_include_markdown_plugin/process.py
  tests/test_unit/test_process.py
Labels: enhancement

#257 Update JSONSchema
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  pyproject.toml
  schema.json
Labels: chore

#258 Fix internal anchors in included file not correctly rewritten
  pyproject.toml
  src/mkdocs_include_markdown_plugin/process.py
  tests/test_unit/test_include.py
  tests/test_unit/test_include_markdown.py
Labels: bug fix
